version: '3.8'

services:
  tomcat:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps/
    container_name: apiStudent
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/studentdb"
  mongodb:
    image: mongo:latest
    container_name: student-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: